name: Profile metrics

on:
  schedule:
    - cron: "0 3 */6 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@1a5109cfed6faf59ffe606435b73006ca76b0e4d # master, fixes achievements/projectsV2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          theme: dark
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_calendar: yes
          plugin_achievements: no
          plugin_achievements_threshold: C
